export const CLEAR_STATE= 'comments/CLEAR_STATE'
export const LOAD_SUCCESS = 'comments/LOAD_SUCCESS'
export const LOAD_FAILED = 'comments/LOAD_FAILED'
export const LOAD_START = 'comments/LOAD_START'
export const UPVOTE = 'comments/UPVOTE'
export const UNDO_UPVOTE = 'comments/UNDO_UPVOTE'
export const DOWNVOTE = 'comments/DOWNVOTE'
export const UNDO_DOWNVOTE = 'comments/UNDO_DOWNVOTE'