export const START_LOAD = 'posts/START_LOAD'
export const LOAD_FAILED = 'posts/LOAD_FAILED'
export const LOAD_SUCCESS = 'posts/LOAD_SUCCESS'
export const CLEAR_STATE = 'posts/CLEAR_STATE'
export const UPVOTE = 'posts/UPVOTE'
export const UNDO_UPVOTE = 'posts/UNDO_UPVOTE'
export const DOWNVOTE = 'posts/DOWNVOTE'
export const UNDO_DOWNVOTE = 'posts/UNDO_DOWNVOTE'